from turtle import *
penup()
goto(-80,-80)
pendown()
bgcolor("black")
pencolor("white")
pensize(4)
hideturtle()
def width():
    dot()
    forward(19)
    penup()
    forward(19)
    pendown()
    forward(38)
    penup()
    forward(19)
    pendown()
    forward(38)
    penup()
    forward(19)
    pendown()
    forward(19)
    dot()
def length():
    left(90)
    forward(171)
    dot()
    left(90)
def diagonal_1():
    left(45)
    forward(241)
    right(135)
    forward(171)
    right(135)
    forward(241)
width()
length()
width()
length()
diagonal_1()
done()